'use client';

import React, { useRef, useEffect, useState, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import {
  Volume2,
  VolumeX,
  Play,
  Pause,
  Maximize,
  Minimize,
  Settings,
  Captions,
  SkipBack,
  SkipForward,
} from 'lucide-react';
import { cdnClient, VideoQuality } from '@/utilities/cdn/cdn-client';

interface AdaptiveVideoPlayerProps {
  videoId: string;
  title: string;
  poster?: string;
  autoplay?: boolean;
  controls?: boolean;
  className?: string;
  onPlay?: () => void;
  onPause?: () => void;
  onEnded?: () => void;
  onError?: (error: Error) => void;
  onQualityChange?: (quality: keyof VideoQuality) => void;
  onTimeUpdate?: (currentTime: number, duration: number) => void;
}

interface CaptionTrack {
  id: string;
  language: string;
  label: string;
  url: string;
  isDefault: boolean;
  isAutoGenerated: boolean;
  format: 'vtt' | 'srt' | 'ass';
}

interface VideoChapter {
  id: string;
  title: string;
  startTime: number;
  endTime?: number;
  description?: string;
  thumbnailUrl?: string;
}

const AdaptiveVideoPlayer: React.FC<AdaptiveVideoPlayerProps> = ({
  videoId,
  title,
  poster,
  autoplay = false,
  controls = true,
  className = '',
  onPlay,
  onPause,
  onEnded,
  onError,
  onQualityChange,
  onTimeUpdate,
}) => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const hlsRef = useRef<any>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [volume, setVolume] = useState(1);
  const [isMuted, setIsMuted] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [showControls, setShowControls] = useState(true);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Quality and streaming
  const [availableQualities, setAvailableQualities] =
    useState<VideoQuality | null>(null);
  const [currentQuality, setCurrentQuality] =
    useState<keyof VideoQuality>('720p');
  const [isHLS, setIsHLS] = useState(false);
  const [hlsUrl, setHlsUrl] = useState<string | null>(null);

  // Captions
  const [captions, setCaptions] = useState<CaptionTrack[]>([]);
  const [activeCaption, setActiveCaption] = useState<CaptionTrack | null>(null);
  const [showCaptions, setShowCaptions] = useState(false);

  // Chapters
  const [chapters, setChapters] = useState<VideoChapter[]>([]);
  const [currentChapter, setCurrentChapter] = useState<VideoChapter | null>(
    null
  );

  // Settings
  const [showSettings, setShowSettings] = useState(false);
  const [playbackRate, setPlaybackRate] = useState(1);
  const [showQualityMenu, setShowQualityMenu] = useState(false);

  // Initialize video player
  useEffect(() => {
    const initializePlayer = async () => {
      try {
        setIsLoading(true);
        setError(null);

        // Load video qualities
        const qualities = await cdnClient.getVideoQualities(videoId);
        setAvailableQualities(qualities);

        // Try HLS first, fallback to MP4
        try {
          const hlsPlaylistUrl = await cdnClient.getHLSPlaylistUrl(videoId);
          setHlsUrl(hlsPlaylistUrl);
          setIsHLS(true);
        } catch (hlsError) {
          console.warn('HLS not available, falling back to MP4');
          setIsHLS(false);
        }

        // Load captions (mock data for now)
        const mockCaptions: CaptionTrack[] = [
          {
            id: 'en',
            language: 'en',
            label: 'English',
            url: `/captions/${videoId}/en.vtt`,
            isDefault: true,
            isAutoGenerated: false,
            format: 'vtt',
          },
          {
            id: 'es',
            language: 'es',
            label: 'Spanish',
            url: `/captions/${videoId}/es.vtt`,
            isDefault: false,
            isAutoGenerated: true,
            format: 'vtt',
          },
        ];
        setCaptions(mockCaptions);
        setActiveCaption(mockCaptions.find(c => c.isDefault) || null);

        // Load chapters (mock data for now)
        const mockChapters: VideoChapter[] = [
          {
            id: '1',
            title: 'Introduction',
            startTime: 0,
            endTime: 30,
            description: 'Welcome to this video',
          },
          {
            id: '2',
            title: 'Main Content',
            startTime: 30,
            endTime: 120,
            description: 'The main part of the video',
          },
        ];
        setChapters(mockChapters);
      } catch (err) {
        const error =
          err instanceof Error
            ? err
            : new Error('Failed to initialize video player');
        setError(error.message);
        onError?.(error);
      } finally {
        setIsLoading(false);
      }
    };

    initializePlayer();
  }, [videoId, onError]);

  // Setup HLS or MP4 playback
  useEffect(() => {
    if (!videoRef.current || isLoading) return;

    const setupPlayback = async () => {
      try {
        if (isHLS && hlsUrl) {
          // Setup HLS.js
          if (typeof window !== 'undefined' && (window as any).Hls) {
            const Hls = (window as any).Hls;

            if (Hls.isSupported()) {
              hlsRef.current = new Hls({
                enableWorker: true,
                lowLatencyMode: true,
                backBufferLength: 90,
                maxBufferLength: 30,
                maxMaxBufferLength: 60,
                liveSyncDurationCount: 3,
                liveMaxLatencyDurationCount: 5,
              });

              hlsRef.current.loadSource(hlsUrl);
              hlsRef.current.attachMedia(videoRef.current);

              hlsRef.current.on(Hls.Events.ERROR, (event: any, data: any) => {
                console.error('HLS error:', data);
                if (data.fatal) {
                  switch (data.type) {
                    case Hls.ErrorTypes.NETWORK_ERROR:
                      hlsRef.current.startLoad();
                      break;
                    case Hls.ErrorTypes.MEDIA_ERROR:
                      hlsRef.current.recoverMediaError();
                      break;
                    default:
                      hlsRef.current.destroy();
                      break;
                  }
                }
              });
            } else if (
              videoRef.current.canPlayType('application/vnd.apple.mpegurl')
            ) {
              // Native HLS support (Safari)
              videoRef.current.src = hlsUrl;
            }
          }
        } else {
          // Setup MP4 playback
          const videoUrl = availableQualities?.[currentQuality];
          if (videoUrl) {
            videoRef.current.src = videoUrl;
          }
        }
      } catch (err) {
        console.error('Error setting up playback:', err);
        setError('Failed to setup video playback');
      }
    };

    setupPlayback();

    return () => {
      if (hlsRef.current) {
        hlsRef.current.destroy();
      }
    };
  }, [isHLS, hlsUrl, availableQualities, currentQuality, isLoading]);

  // Event handlers
  const handlePlay = useCallback(() => {
    if (videoRef.current) {
      videoRef.current.play();
      setIsPlaying(true);
      onPlay?.();
    }
  }, [onPlay]);

  const handlePause = useCallback(() => {
    if (videoRef.current) {
      videoRef.current.pause();
      setIsPlaying(false);
      onPause?.();
    }
  }, [onPause]);

  const handleTimeUpdate = useCallback(() => {
    if (videoRef.current) {
      const current = videoRef.current.currentTime;
      const dur = videoRef.current.duration;
      setCurrentTime(current);
      setDuration(dur);
      onTimeUpdate?.(current, dur);

      // Update current chapter
      const chapter = chapters.find(
        c => current >= c.startTime && current < (c.endTime || duration)
      );
      setCurrentChapter(chapter || null);
    }
  }, [chapters, duration, onTimeUpdate]);

  const handleSeek = useCallback((time: number) => {
    if (videoRef.current) {
      videoRef.current.currentTime = time;
    }
  }, []);

  const handleVolumeChange = useCallback((newVolume: number) => {
    if (videoRef.current) {
      videoRef.current.volume = newVolume;
      setVolume(newVolume);
      setIsMuted(newVolume === 0);
    }
  }, []);

  const handleMute = useCallback(() => {
    if (videoRef.current) {
      if (isMuted) {
        videoRef.current.volume = volume;
        setIsMuted(false);
      } else {
        videoRef.current.volume = 0;
        setIsMuted(true);
      }
    }
  }, [isMuted, volume]);

  const handleQualityChange = useCallback(
    async (quality: keyof VideoQuality) => {
      if (isHLS) {
        // For HLS, change quality level
        if (hlsRef.current) {
          hlsRef.current.currentLevel =
            quality === '1080p' ? 2 : quality === '720p' ? 1 : 0;
        }
      } else {
        // For MP4, change source
        const videoUrl = availableQualities?.[quality];
        if (videoUrl && videoRef.current) {
          const currentTime = videoRef.current.currentTime;
          videoRef.current.src = videoUrl;
          videoRef.current.currentTime = currentTime;
        }
      }

      setCurrentQuality(quality);
      onQualityChange?.(quality);
    },
    [isHLS, availableQualities, onQualityChange]
  );

  const handleFullscreen = useCallback(() => {
    if (containerRef.current) {
      if (!isFullscreen) {
        if (containerRef.current.requestFullscreen) {
          containerRef.current.requestFullscreen();
        }
      } else {
        if (document.exitFullscreen) {
          document.exitFullscreen();
        }
      }
      setIsFullscreen(!isFullscreen);
    }
  }, [isFullscreen]);

  const handleChapterClick = useCallback(
    (chapter: VideoChapter) => {
      handleSeek(chapter.startTime);
    },
    [handleSeek]
  );

  const formatTime = (time: number) => {
    const minutes = Math.floor(time / 60);
    const seconds = Math.floor(time % 60);
    return `${minutes}:${seconds.toString().padStart(2, '0')}`;
  };

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      switch (e.key) {
        case ' ':
          e.preventDefault();
          isPlaying ? handlePause() : handlePlay();
          break;
        case 'ArrowLeft':
          e.preventDefault();
          handleSeek(Math.max(0, currentTime - 10));
          break;
        case 'ArrowRight':
          e.preventDefault();
          handleSeek(Math.min(duration, currentTime + 10));
          break;
        case 'f':
          e.preventDefault();
          handleFullscreen();
          break;
        case 'm':
          e.preventDefault();
          handleMute();
          break;
      }
    },
    [
      isPlaying,
      handlePause,
      handlePlay,
      handleSeek,
      currentTime,
      duration,
      handleFullscreen,
      handleMute,
    ]
  );

  if (error) {
    return (
      <Card className={`p-8 text-center ${className}`}>
        <div className="text-red-500 mb-4">
          <h3 className="text-lg font-semibold">Video Error</h3>
          <p>{error}</p>
        </div>
        <Button onClick={() => window.location.reload()}>Retry</Button>
      </Card>
    );
  }

  return (
    <div
      ref={containerRef}
      className={`relative bg-black rounded-lg overflow-hidden group ${className}`}
      onKeyDown={handleKeyDown}
      tabIndex={0}
      onMouseMove={() => setShowControls(true)}
      onMouseLeave={() => setShowControls(false)}
    >
      {/* Video Element */}
      <video
        ref={videoRef}
        className="w-full h-full"
        poster={poster}
        onPlay={handlePlay}
        onPause={handlePause}
        onTimeUpdate={handleTimeUpdate}
        onLoadedMetadata={() => {
          setDuration(videoRef.current?.duration || 0);
          setIsLoading(false);
        }}
        onEnded={() => {
          setIsPlaying(false);
          onEnded?.();
        }}
        onError={e => {
          const error = new Error('Video playback error');
          setError(error.message);
          onError?.(error);
        }}
        playsInline
        preload="metadata"
      />

      {/* Loading Overlay */}
      {isLoading && (
        <div className="absolute inset-0 bg-black bg-opacity-50 flex items-center justify-center">
          <div className="text-white text-lg">Loading video...</div>
        </div>
      )}

      {/* Controls Overlay */}
      {controls && showControls && (
        <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black to-transparent p-4">
          {/* Progress Bar */}
          <div className="mb-4">
            <div className="relative">
              <Slider
                value={[currentTime]}
                max={duration}
                step={0.1}
                onValueChange={([value]) => handleSeek(value)}
                className="w-full"
              />

              {/* Chapter Markers */}
              {chapters.length > 0 && (
                <div className="absolute top-0 left-0 right-0 h-1">
                  {chapters.map(chapter => (
                    <button
                      key={chapter.id}
                      className="absolute h-1 w-1 bg-white rounded-full opacity-70 hover:opacity-100"
                      style={{
                        left: `${(chapter.startTime / duration) * 100}%`,
                      }}
                      onClick={() => handleChapterClick(chapter)}
                      title={chapter.title}
                    />
                  ))}
                </div>
              )}
            </div>

            {/* Time Display */}
            <div className="flex justify-between text-white text-sm mt-1">
              <span>{formatTime(currentTime)}</span>
              <span>{formatTime(duration)}</span>
            </div>
          </div>

          {/* Control Buttons */}
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              {/* Play/Pause */}
              <Button
                variant="ghost"
                size="sm"
                onClick={isPlaying ? handlePause : handlePlay}
                className="text-white hover:bg-white hover:bg-opacity-20"
              >
                {isPlaying ? <Pause size={20} /> : <Play size={20} />}
              </Button>

              {/* Skip Backward/Forward */}
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleSeek(Math.max(0, currentTime - 10))}
                className="text-white hover:bg-white hover:bg-opacity-20"
              >
                <SkipBack size={20} />
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleSeek(Math.min(duration, currentTime + 10))}
                className="text-white hover:bg-white hover:bg-opacity-20"
              >
                <SkipForward size={20} />
              </Button>

              {/* Volume */}
              <div className="flex items-center space-x-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleMute}
                  className="text-white hover:bg-white hover:bg-opacity-20"
                >
                  {isMuted ? <VolumeX size={20} /> : <Volume2 size={20} />}
                </Button>
                <Slider
                  value={[isMuted ? 0 : volume]}
                  max={1}
                  step={0.1}
                  onValueChange={([value]) => handleVolumeChange(value)}
                  className="w-20"
                />
              </div>

              {/* Current Chapter */}
              {currentChapter && (
                <div className="text-white text-sm ml-4">
                  {currentChapter.title}
                </div>
              )}
            </div>

            <div className="flex items-center space-x-2">
              {/* Captions */}
              {captions.length > 0 && (
                <div className="relative">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setShowCaptions(!showCaptions)}
                    className="text-white hover:bg-white hover:bg-opacity-20"
                  >
                    <Captions size={20} />
                  </Button>

                  {showCaptions && (
                    <div className="absolute bottom-10 right-0 bg-black bg-opacity-90 rounded p-2 min-w-32">
                      {captions.map(caption => (
                        <button
                          key={caption.id}
                          className={`block w-full text-left px-2 py-1 text-sm text-white hover:bg-white hover:bg-opacity-20 rounded ${
                            activeCaption?.id === caption.id
                              ? 'bg-white bg-opacity-20'
                              : ''
                          }`}
                          onClick={() => {
                            setActiveCaption(caption);
                            setShowCaptions(false);
                          }}
                        >
                          {caption.label}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* Quality Selection */}
              {availableQualities && (
                <div className="relative">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setShowQualityMenu(!showQualityMenu)}
                    className="text-white hover:bg-white hover:bg-opacity-20"
                  >
                    {currentQuality}
                  </Button>

                  {showQualityMenu && (
                    <div className="absolute bottom-10 right-0 bg-black bg-opacity-90 rounded p-2 min-w-20">
                      {Object.keys(availableQualities).map(quality => (
                        <button
                          key={quality}
                          className={`block w-full text-left px-2 py-1 text-sm text-white hover:bg-white hover:bg-opacity-20 rounded ${
                            currentQuality === quality
                              ? 'bg-white bg-opacity-20'
                              : ''
                          }`}
                          onClick={() => {
                            handleQualityChange(quality as keyof VideoQuality);
                            setShowQualityMenu(false);
                          }}
                        >
                          {quality}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* Settings */}
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowSettings(!showSettings)}
                className="text-white hover:bg-white hover:bg-opacity-20"
              >
                <Settings size={20} />
              </Button>

              {/* Fullscreen */}
              <Button
                variant="ghost"
                size="sm"
                onClick={handleFullscreen}
                className="text-white hover:bg-white hover:bg-opacity-20"
              >
                {isFullscreen ? <Minimize size={20} /> : <Maximize size={20} />}
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* Settings Panel */}
      {showSettings && (
        <div className="absolute bottom-16 right-4 bg-black bg-opacity-90 rounded p-4 min-w-48">
          <h3 className="text-white text-sm font-semibold mb-2">Settings</h3>

          {/* Playback Speed */}
          <div className="mb-3">
            <label className="text-white text-xs block mb-1">
              Playback Speed
            </label>
            <Select
              value={playbackRate.toString()}
              onValueChange={value => {
                setPlaybackRate(parseFloat(value));
                if (videoRef.current) {
                  videoRef.current.playbackRate = parseFloat(value);
                }
              }}
            >
              <SelectTrigger className="w-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="0.5">0.5x</SelectItem>
                <SelectItem value="0.75">0.75x</SelectItem>
                <SelectItem value="1">1x</SelectItem>
                <SelectItem value="1.25">1.25x</SelectItem>
                <SelectItem value="1.5">1.5x</SelectItem>
                <SelectItem value="2">2x</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Captions */}
          {captions.length > 0 && (
            <div className="mb-3">
              <label className="text-white text-xs block mb-1">Captions</label>
              <Select
                value={activeCaption?.id || 'off'}
                onValueChange={value => {
                  if (value === 'off') {
                    setActiveCaption(null);
                  } else {
                    const caption = captions.find(c => c.id === value);
                    setActiveCaption(caption || null);
                  }
                }}
              >
                <SelectTrigger className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="off">Off</SelectItem>
                  {captions.map(caption => (
                    <SelectItem key={caption.id} value={caption.id}>
                      {caption.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}
        </div>
      )}

      {/* Caption Track */}
      {activeCaption && showCaptions && (
        <track
          kind="captions"
          src={activeCaption.url}
          srcLang={activeCaption.language}
          label={activeCaption.label}
          default={activeCaption.isDefault}
        />
      )}
    </div>
  );
};

export default AdaptiveVideoPlayer;
